### ISSUE TITLE
Add specification in `oasis compile` or add config to specify --max-mem flag in wasm-build

### ISSUE THREAD

**Issue by david-yan** [oasislabs/oasis-compile#5]

**Comment by armaniferrante** [comment]
If we want to have project-specific configurations, then I propose we add to a `package.metadata.oasis` section to each rust-contract's Cargo.toml  that wants to set custom configs. 

Cargo will ignore such metadata sections in the Cargo.toml and so it seems like the appropriate place for something like this. 

See https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table-optional

**Comment by david-yan** [comment]
Nice find! This looks like a pretty good solution.

**Comment by armaniferrante** [comment]
Handled by #43
